version: '3.8'

services:
  video-downloader:
    build: .
    container_name: video_downloader
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    restart: unless-stopped
